name: CI
on:
  push:
  pull_request:
    branches: [main]

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - run: gofmt -l . | tee /dev/stderr | (! grep .)
      - run: go vet ./...
      - run: go build ./...
      - run: go test ./...

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ludeeus/action-shellcheck@master
        with:
          scandir: './scripts'
